(function(g){var m=window.AmazonUIPageJS||window.P,p=m._namespace||m.attributeErrors,e=p?p("TwisterHardlinesDetailPageAsset"):m;e.guardFatal?e.guardFatal(g)(e,window):e.execute(function(){g(e,window)})})(function(g,m,p){g.when("A","jQuery","atf").execute(function(e,c){e.on.ready(function(){function d(a,b,d,e,f){c(a).slideToggle(300);c(b).slideToggle(300);c(d).toggleClass("tmmShowPrompt tmmHidePrompt");c(e).toggleClass("tmmShowPrompt tmmHidePrompt");c(f).toggleClass("rotate")}function k(a){a.position();
a.width();c(".swatchElement");a.find(".swatchElement").each(function(){c(this).attr("data-width",c(this).width())});c("#formats").find(".a-row").removeClass("nonJSFormats")}function b(){var a=c("#formats"),b=a.width()-40,d=0;a.find(".swatchElement").each(function(){c(this).is(":visible")&&(d+=c(this).width())});d>b?c(a.find(".swatchElement:visible").get().reverse()).each(function(){var a=0,e=!1;c(this).find(".format").hasClass("a-button-selected")?(a=c(this).prev(".swatchElement").width(),e=c(this).prev(".swatchElement").is(":hidden"),
c(this).prev(".swatchElement").hide()):(a=c(this).width(),e=c(this).is(":hidden"),c(this).hide());e||(d-=a);return d>b}):d<b&&a.find(".swatchElement").each(function(){if(c(this).is(":hidden"))return c(this).attr("data-width")<=b-d&&c(this).show(),!1})}var a=0,f=0,l,n=function(a){"undefined"!=typeof a&&(l=new a.ImpressionLogger("dpbxapps","bxapps-atfMarker",!0,!0))};"undefined"!=typeof amznJQ?amznJQ.available("DPClientLogger",function(){n(m.DPClientLogger)}):g.when("DPClientLogger").execute(n);e.declarative("tmm-see-more-editions-click",
["click"],function(a){var b=a.data,f=b.metabindingUrl;if(a.$target.hasClass("a-link-expander")||a.$target.parent().hasClass("a-link-expander")){var b=b.metabindingPlaceHolder,g="#metabinding_row_top_"+b,h="#metabinding_row_bottom_"+b,k="#editionsSeePrompt_"+b,l="#editionsHidePrompt_"+b,n="#editionsIcon_"+b,p="isAjaxComplete_"+b,q="isAjaxInProgress_"+b;a="#tmmSpinnerDiv_"+b;var E=e.state("mediamatrix-state"),b=E["url_"+b].replace(/&amp;/g,"&");c("#formats .tmmErrorClass").hide();"1"===E[p]||"1"===
E[q]?d(g,h,k,l,n):(e.ajax(b,{method:"get",success:function(){E[p]="1";e.state("mediamatrix-state",E);d(g,h,k,l,n)},indicator:c(a),error:function(){c($tmmErrorDiv).show();E[q]="0";e.state("mediamatrix-state",E)}}),E[q]="1",e.state("mediamatrix-state",E))}else"#"!==f&&(m.location=f)});if(0<c("#formats > .a-link-expander").length){var h=m.ue;h&&h.count&&h.count("mediaMatrixExpanderPresent",1)}c("#formats > .a-link-expander").click(function(){d("#tmmSwatches","#twister","#showMoreFormatsPrompt","#hideMoreFormatsPrompt",
"#formatsIcon");if(!f){var b=m.ue;b&&b.count&&b.count("mediaMatrixExpanderClicked",1);f=1}l&&c("#twister").is(":visible")&&!a&&(l.logImpression("tmm-show-more-formats-viewed"),a=1)});var h=e.state("mediamatrix-state"),p="1";"undefined"!==typeof h&&"undefined"!==typeof h.showHybridMediaMatrix&&"1"===h.showHybridMediaMatrix?p="0":"undefined"!==typeof h&&"undefined"!==typeof h.isDvdWeblabEnabled&&"1"===h.isDvdWeblabEnabled&&(p="0");"1"===p&&(c("#formats.responsive").each(function(){k(c(this))}),b(),
e.on("resize",b));c("#formats .unselected .format").mouseenter(function(){c(this).find(".a-color-secondary").addClass("a-color-price").removeClass("a-color-secondary")}).mouseleave(function(){c(this).find(".a-color-price").addClass("a-color-secondary").removeClass("a-color-price")});c("#landingItemRentalLink").attr("href","javascript:document.getElementById('rentBuySection').click();")})});g.when("A","jQuery","a-dropdown").execute(function(e,c,d){function g(a){return a?a.replace(/&#0/g,"&#"):undef}
function b(a){for(var b=a.getOptions(),b=b?b.size():0,c=1;c<b;c++)a.removeOption(1)}function a(a,b){var d=a.getOption(0),e=d.info()[0];d.remove();c.each(b,function(b,c){a.addOption({text:J[g(c)],value:c,css_class:"dropdownAvailable"},1)});a.addOption(e,0);a.val(e.value)}function f(c){H=c.value;b(w);"-1"!==H&&(l(),a(w,Object.keys(p[g(H)])))}function l(){Object.keys||(Object.keys=function(){var a=Object.prototype.hasOwnProperty,b=!{toString:null}.propertyIsEnumerable("toString"),c="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),
d=c.length;return function(e){if("object"!==typeof e&&("function"!==typeof e||null===e))throw new TypeError("Object.keys called on non-object");var f=[],g;for(g in e)a.call(e,g)&&f.push(g);if(b)for(g=0;g<d;g++)a.call(e,c[g])&&f.push(c[g]);return f}}())}function n(a){A=a.value;"-1"!==A&&"-1"!==H&&(m.location=N[p[g(H)][g(A)]])}function h(a){a=a.value;"-1"!==a&&(m.location=N[g(a)])}var p,r=e.state("dcdMetaData");if(r){var N=r.asinToDetailPageURLMap,J=r.truncatedValuesMap,L=r.dimensionKeys,v=L[0],H=-1,
A=-1,w;2===L.length?(p=r.doubleValuesToAsinMap,r=L[1],L=d.getSelect("native_dcd_dropdown_"+v),w=d.getSelect("native_dcd_dropdown_"+r),L.setValue("-1"),w.setValue("-1"),b(w),e.on("a:dropdown:selected:"+v,f),e.on("a:dropdown:selected:"+r,n)):(L=d.getSelect("native_dcd_dropdown_"+v),(d=r.selectedAsin)?L.setValue(d):L.setValue("-1"),e.on("a:dropdown:selected:asin-redirect",h))}})});
/* ******** */
(function(g){var m=window.AmazonUIPageJS||window.P,p=m._namespace||m.attributeErrors,e=p?p("PInfoHardlinesDetailPageAsset"):m;e.guardFatal?e.guardFatal(g)(e,window):e.execute(function(){g(e,window)})})(function(g,m,p){g.when("A","jQuery","atf").execute(function(e,c,d){function g(){var b=parseInt(c("#byline").width()),a=0;c("#byline .author").each(function(){c(this).is(".notFaded")&&(a+=c(this).outerWidth())});a+=c("#byline .more").outerWidth();if(a>b){var d=c("#byline .author.notFaded").length;c(c("#byline .author.notFaded").get().reverse()).each(function(e){a>
b&&e<d-1&&(e=c(this).width(),c(this).removeClass("notFaded"),c(this).fadeOut(10,function(){c(this).hide()}),a-=e,c("#byline .moreCount").html(c("#byline .author").length-c("#byline .author.notFaded").length),c("#byline .more").addClass("notFaded").fadeIn(10))})}else if(a<b&&c("#byline .author.notFaded").length<c("#byline .author").length){var e=b-a;c("#byline .author").each(function(){if(!c(this).hasClass("notFaded")){var a=c(this).outerWidth();a<=e?(e-=a,c(this).addClass("notFaded").fadeIn(10),a=
c("#byline .author").length-c("#byline .author.notFaded").length,0===a?c("#byline .more").removeClass("notFaded").fadeOut(10):(c("#byline .moreCount").html(a),c("#byline .more").addClass("notFaded").fadeIn(10))):e=0}})}}c("#byline .showMoreLink").click(function(){c("#byline .author").each(function(){c(this).hasClass("notFaded")||c(this).addClass("notFaded").fadeIn(0);c("#byline .more").removeClass("notFaded").fadeOut(0)});return!1});c("#byline .contributorNameID").mouseenter(function(){var b=c(this).attr("data-asin"),
a={},d="isAjaxComplete_"+b,g="isAjaxInProgress_"+b,k=e.state("popoverImage-state");a.entityID=b;"1"!==k[d]&&"1"!==k[g]&&(c.ajax({url:"/gp/product/utility/by-line/book-contributor-details/ajax/author-image.html",data:a,dataType:"html",timeout:1E3,success:function(a){c("#contributorImageContainer"+b).get(0).innerHTML=a;k[d]="1";e.state("popoverImage-state",k)},error:function(){k[g]="0";e.state("popoverImage-state",k)}}),k[g]="1",e.state("popoverImage-state",k))});(function(b){var a=parseInt(b.width()),
d=parseInt(b.find(".more").outerWidth()),e=0;c("#byline .author").each(function(){c(this).is(".notFaded")&&(e+=c(this).outerWidth())});c("#byline .more").attr("data-width",d);var g=a-d;if(g>e)b.find(".author").each(function(){var a=c(this).index();3<=parseInt(a)?(a=c(this).outerWidth(),c(this).attr("data-width",a),a<g?(g-=a,c(this).addClass("notFaded"),c(this).fadeIn("slow")):(g=0,c(this).fadeOut("slow"))):(a=c(this).outerWidth(),c(this).attr("data-width",a),g-=a)});else{var h=c("#byline .author.notFaded").length;
c(c("#byline .author.notFaded").get().reverse()).each(function(a){g<e&&a<h-1&&(a=c(this).outerWidth(),e-=a,c(this).fadeOut("slow").removeClass("notFaded"))})}a=b.find(".author").length-b.find(".author.notFaded").length;0<a&&(b.find(".moreCount").html(a),b.find(".more").fadeIn("slow"),b.find(".more").addClass("notFaded"))})(e.$("#byline"));c(m).resize(function(){g()})});g.when("A","jQuery","atf").execute(function(e,c,d){function g(){var b=parseInt(c("#bylineInfo").width()),a=0;c("#bylineInfo .author").each(function(){c(this).is(".notFaded")&&
(a+=c(this).outerWidth())});a+=c("#bylineInfo .more").outerWidth();if(a>b){var d=c("#bylineInfo .author.notFaded").length;c(c("#bylineInfo .author.notFaded").get().reverse()).each(function(e){a>b&&e<d-1&&(e=c(this).width(),c(this).removeClass("notFaded"),c(this).fadeOut(10,function(){c(this).hide()}),a-=e,c("#bylineInfo .moreCount").html(c("#bylineInfo .author").length-c("#bylineInfo .author.notFaded").length),c("#bylineInfo .more").addClass("notFaded").fadeIn(10))})}else if(a<b&&c("#bylineInfo .author.notFaded").length<
c("#bylineInfo .author").length){var e=b-a;c("#bylineInfo .author").each(function(){if(!c(this).hasClass("notFaded")){var a=c(this).outerWidth();a<=e?(e-=a,c(this).addClass("notFaded").fadeIn(10),a=c("#bylineInfo .author").length-c("#bylineInfo .author.notFaded").length,0===a?c("#bylineInfo .more").removeClass("notFaded").fadeOut(10):(c("#bylineInfo .moreCount").html(a),c("#bylineInfo .more").addClass("notFaded").fadeIn(10))):e=0}})}}c("#bylineInfo .showMoreLink").click(function(){c("#bylineInfo .author").each(function(){c(this).hasClass("notFaded")||
c(this).addClass("notFaded").fadeIn(0);c("#bylineInfo .more").removeClass("notFaded").fadeOut(0)});return!1});c("#bylineInfo .contributorNameID").mouseenter(function(){var b=c(this).attr("data-asin"),a={},d="isAjaxComplete_"+b,g="isAjaxInProgress_"+b,k=e.state("popoverImage-state");a.entityID=b;"1"!==k[d]&&"1"!==k[g]&&(c.ajax({url:"/gp/product/utility/by-line/book-contributor-details/ajax/author-image.html",data:a,dataType:"html",timeout:1E3,success:function(a){c("#contributorImageContainer"+b).get(0).innerHTML=
a;k[d]="1";e.state("popoverImage-state",k)},error:function(){k[g]="0";e.state("popoverImage-state",k)}}),k[g]="1",e.state("popoverImage-state",k))});(function(b){var a=parseInt(b.width()),d=parseInt(b.find(".more").outerWidth()),e=0;c("#bylineInfo .author").each(function(){c(this).is(".notFaded")&&(e+=c(this).outerWidth())});c("#bylineInfo .more").attr("data-width",d);var g=a-d;if(g>e)b.find(".author").each(function(){var a=c(this).index();3<=parseInt(a)?(a=c(this).outerWidth(),c(this).attr("data-width",
a),a<g?(g-=a,c(this).addClass("notFaded"),c(this).fadeIn("slow")):(g=0,c(this).fadeOut("slow"))):(a=c(this).outerWidth(),c(this).attr("data-width",a),g-=a)});else{var h=c("#bylineInfo .author.notFaded").length;c(c("#bylineInfo .author.notFaded").get().reverse()).each(function(a){g<e&&a<h-1&&(a=c(this).outerWidth(),e-=a,c(this).fadeOut("slow").removeClass("notFaded"))})}a=b.find(".author").length-b.find(".author.notFaded").length;0<a&&(b.find(".moreCount").html(a),b.find(".more").fadeIn("slow"),b.find(".more").addClass("notFaded"))})(e.$("#bylineInfo"));
c(m).resize(function(){g()})});g.when("A","jQuery").register("product-description-fix",function(e,c){return{fixTableIssue:function(){c("#productDescription .productDescriptionWrapper table").each(function(){var d=c(this).attr("width");"undefined"!==typeof d?c(this).css("width",d):c(this).css("width","auto")})}}})});
/* ******** */
(function(g){var m=window.AmazonUIPageJS||window.P,p=m._namespace||m.attributeErrors,e=p?p("OffersHardlinesDetailPageAsset"):m;e.guardFatal?e.guardFatal(g)(e,window):e.execute(function(){g(e,window)})})(function(g,m,p){g.when("A","jQuery","atf").register("accordionBuyBoxJS",function(e,c,d){var k={updateCssClass:function(b){var a=c("#rbbContainer");a.find(".selected .a-icon-radio-active").removeClass("a-icon-radio-active").addClass("a-icon-radio-inactive");a.find(".selected .offer-price").removeClass("a-color-price").addClass("a-color-secondary");
b.parents(".rbbSection").removeClass("unselected").addClass("selected");b.parents(".rbbSection").toggleClass("dp-accordion-active",500);b.find(".a-icon-radio-inactive").removeClass("a-icon-radio-inactive").addClass("a-icon-radio-active");b.find(".offer-price").removeClass("a-color-secondary").addClass("a-color-price");c("#rbbContainer .rbbSection .rbbContent").find(".offer-price").removeClass("a-color-secondary").addClass("a-color-price")},animate:function(b){var a=c("#rbbContainer"),d=b.attr("id"),
e,g;a.find(".rbbSection").each(function(a,b){c(b).find(".rbbHeader")[0].id==d?e=c(b):c(b).hasClass("selected")&&(g=c(b))});g.find(".rbbContent").slideUp(500,function(){g.removeClass("selected").addClass("unselected");g.toggleClass("dp-accordion-active",500)});e.find(".rbbContent").slideDown(500);c.browser.msie&&7==parseInt(c.browser.version,10)&&(e.find(".rbbContent").css("display","inline"),setTimeout(function(){e.find(".rbbContent").css("display","block")},505))},oneClickJS:function(){c("#one-click-button, #one-click-button-ubb").click(function(){var b=
"https://"+m.location.host+c("#addToCart").attr("action");c("#addToCart").attr("action",b);return!0})},usedBuyBoxJS:function(){c("#one-click-button-ubb, #usedbuyBox #add-to-cart-button-ubb").click(function(){var b=c("#addToCart"),a=b.attr("action").replace("ref=dp_start-bbf_1_glance","ref=dp_start-ubbf_1_glance");b.attr("action",a);return!0});g.when("a-popover").execute(function(b){var a=c("#usedItemConditionInfoLink"),d=b.create(a,{width:250,position:"triggerBottom",activate:e.capabilities.touch?
"onmousemove":"onclick",closeButton:!1,popoverLabel:"Used condition details",name:"usedItemConditionDetailsPopover",dataStrategy:"preload"});a.mouseleave(function(){d.hide()})})},initialize:function(){c(".rbbHeaderLink").attr("href","javascript:void(0);");c("#rbbContainer .rbbSection.unselected .dp-accordion-inner").hide();c("#rbbContainer .rbbSection .rbbHeader").click(function(b){c(b.target);b=c(this);var a=b.hasClass("rbbHeader")?b:b.parents(".rbbHeader");if(a.parents(".rbbSection").hasClass("selected"))return!1;
b=c("#rbbContainer .rbbSection.selected .rbbHeader").attr("id");var d=a.attr("id");k.updateCssClass(a);c("#abbWrapper [id^=mbb-offeringID-]").each(function(){this.checked=!1});a=c(this);k.animate(a);e.trigger("buybox:accordion:changed",d,b);return!0});k.oneClickJS();k.usedBuyBoxJS()}};return k})});
/* ******** */
(function(a){var c=window.AmazonUIPageJS||window.P,d=c._namespace||c.attributeErrors,b=d?d("DetailPagePromotionalBundleAssets"):c;b.guardFatal?b.guardFatal(a)(b,window):b.execute(function(){a(b,window)})})(function(a,c,d){a.when("A","ready").execute("kbpMobileExpander",function(b){var a=b.$;a(".pb-bundle-section-expander").click(function(b){a(".pb-bundle-mobile-box").removeClass("aok-hidden");a(".pb-bundle-expander-box").addClass("aok-hidden")})})});
/* ******** */
